import 'package:material_ui/material_ui.dart';
import 'package:spark/src/core/design_system/theme/action_icon_theme.dart';
import 'package:spark/src/core/design_system/theme/color_scheme.dart';
import 'package:spark/src/core/design_system/theme/text_theme.dart';

/// Adapts Spark's SDK theme tokens to the editor's standalone Material types.
ThemeData get editorTheme {
  const colors = AppColorScheme.dark;
  final text = AppTextTheme.dark;
  return ThemeData(
    useMaterial3: true,
    actionIconTheme: ActionIconThemeData(
      backButtonIconBuilder: appActionIconTheme.backButtonIconBuilder,
      closeButtonIconBuilder: appActionIconTheme.closeButtonIconBuilder,
      drawerButtonIconBuilder: appActionIconTheme.drawerButtonIconBuilder,
      endDrawerButtonIconBuilder: appActionIconTheme.endDrawerButtonIconBuilder,
    ),
    colorScheme: ColorScheme(
      brightness: colors.brightness,
      primary: colors.primary,
      onPrimary: colors.onPrimary,
      primaryContainer: colors.primaryContainer,
      onPrimaryContainer: colors.onPrimaryContainer,
      primaryFixed: colors.primaryFixed,
      primaryFixedDim: colors.primaryFixedDim,
      onPrimaryFixed: colors.onPrimaryFixed,
      onPrimaryFixedVariant: colors.onPrimaryFixedVariant,
      secondary: colors.secondary,
      onSecondary: colors.onSecondary,
      secondaryContainer: colors.secondaryContainer,
      onSecondaryContainer: colors.onSecondaryContainer,
      secondaryFixed: colors.secondaryFixed,
      secondaryFixedDim: colors.secondaryFixedDim,
      onSecondaryFixed: colors.onSecondaryFixed,
      onSecondaryFixedVariant: colors.onSecondaryFixedVariant,
      tertiary: colors.tertiary,
      onTertiary: colors.onTertiary,
      tertiaryContainer: colors.tertiaryContainer,
      onTertiaryContainer: colors.onTertiaryContainer,
      tertiaryFixed: colors.tertiaryFixed,
      tertiaryFixedDim: colors.tertiaryFixedDim,
      onTertiaryFixed: colors.onTertiaryFixed,
      onTertiaryFixedVariant: colors.onTertiaryFixedVariant,
      error: colors.error,
      onError: colors.onError,
      errorContainer: colors.errorContainer,
      onErrorContainer: colors.onErrorContainer,
      surface: colors.surface,
      onSurface: colors.onSurface,
      surfaceDim: colors.surfaceDim,
      surfaceBright: colors.surfaceBright,
      surfaceContainerLowest: colors.surfaceContainerLowest,
      surfaceContainerLow: colors.surfaceContainerLow,
      surfaceContainer: colors.surfaceContainer,
      surfaceContainerHigh: colors.surfaceContainerHigh,
      surfaceContainerHighest: colors.surfaceContainerHighest,
      onSurfaceVariant: colors.onSurfaceVariant,
      outline: colors.outline,
      outlineVariant: colors.outlineVariant,
      shadow: colors.shadow,
      scrim: colors.scrim,
      inverseSurface: colors.inverseSurface,
      onInverseSurface: colors.onInverseSurface,
      inversePrimary: colors.inversePrimary,
      surfaceTint: colors.surfaceTint,
    ),
    textTheme: TextTheme(
      displayLarge: text.displayLarge,
      displayMedium: text.displayMedium,
      displaySmall: text.displaySmall,
      headlineLarge: text.headlineLarge,
      headlineMedium: text.headlineMedium,
      headlineSmall: text.headlineSmall,
      titleLarge: text.titleLarge,
      titleMedium: text.titleMedium,
      titleSmall: text.titleSmall,
      bodyLarge: text.bodyLarge,
      bodyMedium: text.bodyMedium,
      bodySmall: text.bodySmall,
      labelLarge: text.labelLarge,
      labelMedium: text.labelMedium,
      labelSmall: text.labelSmall,
    ),
  );
}
