name: sparksocial
description: "Spark mobile app"
publish_to: "none"
# The number after + should stay fixed, the android workflow will change it on every build
version: 0.4.0+1
environment:
  sdk: ^3.8.1
workspace:
  - widgetbook
  - fonts
  - assets

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.1
  camera: ^0.11.1
  path_provider: ^2.1.2
  flutter_svg: ^2.2.0
  atproto: ^0.13.3
  bluesky: ^0.18.10
  http: ^1.2.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.3
  fvp: ^0.35.0
  fluentui_system_icons: ^1.1.273
  image_picker: ^1.0.7
  path: ^1.9.1
  image: ^4.5.4
  flutter_cache_manager: ^3.3.1
  synchronized: ^3.1.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  auto_route: ^10.1.0+1
  flutter_secure_storage: ^9.2.4
  atproto_core: ^0.11.2
  sqflite: ^2.4.2
  pool: ^1.5.0
  collection: ^1.19.1
  carousel_slider: ^5.0.0
  web_socket_channel: ^3.0.3
  any_link_preview: ^3.0.3
  better_player_plus: ^1.1.5
  intl: ^0.20.2
  video_player: ^2.10.0
  gradient_borders: ^1.0.1
  fonts:
    path: fonts
  assets:
    path: assets
  posthog_flutter: ^5.6.0
  pro_image_editor: ^12.0.0-beta.4
  google_fonts: ^6.3.2
  flutter_colorpicker: ^1.1.0

  pro_video_editor:
    git:
      url: https://github.com/sprksocial/pro_video_editor.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1
  auto_route_generator: ^10.2.3
  flutter_launcher_icons: ^0.14.3
  very_good_analysis: ^9.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter_native_splash:
  color: "#000000"
  background_image: assets/branding/splash.png
  color_dark: "#000000"
  android_12:
    color: "#000000"
    background_image: assets/branding/splash.png
    color_dark: "#000000"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/sprk.svg
  fonts:
    - family: Fraunces
      fonts:
        - asset: packages/fonts/Fraunces-Variable.ttf
    - family: SN Pro
      fonts:
        - asset: packages/fonts/SNPro-Variable.ttf
