name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.14.0
  widgetbook_annotation: ^3.6.0
  sparksocial:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.14.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  fonts:
    - family: Fraunces
      fonts:
        - asset: assets/fonts/Fraunces-Variable.ttf
    - family: SN Pro
      fonts:
        - asset: assets/fonts/SNPro-Variable.ttf