name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.22.0
  widgetbook_annotation: ^3.11.0
  spark:
    path: ../
  fonts:
    path: ../fonts
  assets:
    path: ../assets
  flutter_riverpod: ^3.0.3
  fluentui_system_icons: ^1.1.273

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.22.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  fonts:
    - family: Fraunces
      fonts:
        - asset: packages/fonts/Fraunces-Variable.ttf
    - family: SN Pro
      fonts:
        - asset: packages/fonts/SNPro-Variable.ttf
