name: "Internal testing android release"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.29.2
          cache: true

      - name: Setup keys
        uses: timheuer/base64-to-file@v1
        with:
          fileName: "keystore/upload_key.jks"
          encodedString: ${{ secrets.SIGNING_KEY_BASE64 }}

      - name: Setup env
        run: |
          echo "VIDEO_SERVICE_URL=${{ secrets.VIDEO_SERVICE_URL }}" >> .env
          echo "SPRK_APPVIEW_URL=${{ secrets.SPRK_APPVIEW_URL }}" >> .env
          echo "SIGNUPS_DISABLED=${{ secrets.SIGNUPS_DISABLED }}" >> .env

      - name: Set versionCode (commit count + run attempt)
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          BUILD_ATTEMPT=${{ github.run_attempt }}
          VERSION_CODE=$((COMMIT_COUNT * 10 + BUILD_ATTEMPT))
          sed -i "s/^\(version:.*\)+[0-9]*\$/\1+${VERSION_CODE}/" pubspec.yaml
          echo "Using versionCode: $VERSION_CODE"

      - name: Configure Keystore
        run: |
          echo "storeFile=/home/runner/work/_temp/keystore/upload_key.jks" >> key.properties
          echo "storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}" >> key.properties
          echo "keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}" >> key.properties
          echo "keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}" >> key.properties
        working-directory: android

      - name: Build PlayStore AAB
        run: |
          flutter build appbundle

      - name: Upload AAB to PlayStore
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: so.sprk.app
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
