name: Flutter Analyze Changed Files

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed Dart files
        id: changed_files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            **/*.dart

      - name: Set up Flutter
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.38.4
          cache: true

      - name: Codegen
        if: steps.changed_files.outputs.any_changed == 'true'
        run: |
          touch .env
          flutter pub get --enforce-lockfile
          dart run build_runner build --delete-conflicting-outputs
          cd widgetbook
          dart run build_runner build --delete-conflicting-outputs

      - name: Run Flutter Analyze
        id: analyze_step
        if: steps.changed_files.outputs.any_changed == 'true'
        run: flutter analyze --write=flutter_analyze.log

      - name: Flutter Analyze Commenter
        if: ${{ !cancelled() }} # Required to run this step even if failure
        uses: yorifuji/flutter-analyze-commenter@v1
        with:
          analyze-log: flutter_analyze.log
          verbose: false
